//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GroceryEntities : DbContext
    {
        public GroceryEntities()
            : base("name=GroceryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FeedBack> FeedBacks { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<Register> Registers { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<staff> staffs { get; set; }
    }
}
